version: '2'
services:
  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btcd:
    image: btcd
    container_name: btcd
    volumes:
      - shared:/rpc:z
      - bitcoin:/data:z
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS=sb1qfn0unrjcjr80u3p4g29ahjl0wcpp0qzwjjt874
    entrypoint: [ "./start-btcd.sh" ]

  alice:
    image: alice
    build:
      context: docker/lnd
    container_name: alice
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - NOSEEDBACKUP=1
    ports:
      - 10008:10009
    volumes:
      - shared:/rpc:z
      - alice:/root/.lnd:z
    entrypoint: [ "./start-lnd.sh" ]
    links:
      - "btcd:blockchain"
  lnd:
    image: lnd
    build:
      context: docker/lnd
    container_name: lnd
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - NOSEEDBACKUP=1
    ports:
      - 10009:10009
      - 8535:8535
    volumes:
      - shared:/rpc:z
      - lnd:/root/.lnd:z
    entrypoint: [ "./start-lnd.sh" ]

    links:
      - "btcd:blockchain"
  thub:
    image: apotdevin/thunderhub:v0.12.7
    container_name: thub
    depends_on:
      - lnd
    ports:
      - "${THUB_PORT}:${THUB_PORT}"
    volumes:
      - lnd:/root/.lnd:z
      - ${PWD}/docker/accounts.yml:/accounts.yaml:ro
    environment:
      LOG_LEVEL: silly
      ACCOUNT_CONFIG_PATH: /accounts.yaml

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  alice:
    driver: local

  lnd:
    driver: local
